<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>7.3</LangVersion>
    <AssemblyName>ModernKey</AssemblyName>
    <RootNamespace>ModernKey</RootNamespace>
    <ApplicationIcon>Resources\AppIcon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <StartupObject>ModernKey.App</StartupObject>
    <Deterministic>true</Deterministic>
    <Prefer32Bit>false</Prefer32Bit>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Buffers" Version="4.6.1" />
    <PackageReference Include="System.Memory" Version="4.6.3" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
    <PackageReference Include="Sdcb.PaddleOCR" Version="3.3.1" />
    <PackageReference Include="Sdcb.PaddleOCR.Models.Online" Version="3.3.1" />
    <PackageReference Include="OpenCvSharp4.Windows" Version="4.9.0.20240103" />
    <PackageReference Include="Sdcb.PaddleInference.runtime.win64.mkl" Version="3.3.1.70" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\AppIcon.ico" />
    <Resource Include="Resources\StatusViet.ico" />
    <Resource Include="Resources\StatusEng.ico" />
    <None Update="Resources\AppIcon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\StatusViet.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\StatusEng.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.IO.Compression.FileSystem" />
  </ItemGroup>

  <Target Name="EnsurePortableFolder" AfterTargets="Build">
    <MakeDir Directories="$(TargetDir).portable" Condition="!Exists('$(TargetDir).portable')" />
  </Target>

</Project>
