<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>7.3</LangVersion>
    <AssemblyName>ModernKey</AssemblyName>
    <RootNamespace>ModernKey</RootNamespace>
    <ApplicationIcon>Resources\AppIcon.ico</ApplicationIcon>
    <StartupObject>ModernKey.App</StartupObject>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Resources\AppIcon.ico" />
    <Resource Include="Resources\StatusViet.ico" />
    <Resource Include="Resources\StatusEng.ico" />
    <None Update="Resources\AppIcon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\StatusViet.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\StatusEng.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Config\vi_VN.dic">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>

</Project>
