<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>ModernKey</AssemblyName>
    <RootNamespace>ModernKey</RootNamespace>
    <ApplicationIcon>Resources\AppIcon.ico</ApplicationIcon>
    <StartupObject>ModernKey.App</StartupObject>
    <Deterministic>true</Deterministic>
    <!-- Cấu hình Standalone Single-File hiện đại -->
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile Condition="'$(SelfContained)' == 'true'">true</EnableCompressionInSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Resources\AppIcon.ico" />
    <Resource Include="Resources\StatusViet.ico" />
    <Resource Include="Resources\StatusEng.ico" />
    <EmbeddedResource Include="Config\vi_VN.dic" />
    <None Update="Resources\AppIcon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\StatusViet.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\StatusEng.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Config\vi_VN.dic">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
